resume:
pretrain:
seed: 1024
data:
    dataset: k400
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 32
    workers: 0
    num_classes: 400
    image_tmpl: '{:05d}.jpg'
    train_root: 'kinetics400_frames'
    train_list: 'lists/kinetics_400/k400_train.txt'
    val_root: 'kinetics400_frames'
    val_list: 'lists/kinetics_400/k400_train.txt'
    label_list: 'lists/kinetics_400/kinetics_400_labels.txt'
    input_size: 224
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
network:
    arch: ViT-B/32 #Vit-B/16 Vit-L/14
    init: True
    tm: False  # False tsm tokent1d tokenshift
    drop_out: 0.0
    emb_dropout: 0.0
    type: clip_k400
    sim_header: Transf  # Transf   None
    joint_st: False
    drop: 0
    fix_text: True
    fix_video: False
solver:
    type: cosine
    epochs: 5
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: CE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1
