seed: 1024
data:
    dataset: hmdb51
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 8
    workers: 0
    num_classes: 51
    image_tmpl: '{:05d}.jpg'
    val_root: 'hmdb51_frame_org'
    val_list: 'lists/hmdb51/hmdb51_zero_shot.txt'
    label_list: 'lists/hmdb51/hmdb51_labels.txt'
    index_bias: 1
    input_size: 224
network:
    arch: ViT-B/32  #ViT-B/16  #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0
    emb_dropout: 0.0
    type: clip_hmdb
    sim_header: Transf
logging:
    print_freq: 10
    eval_freq: 1